export const GET_CURRENTDATA = 'GET_CURRENTDATA'
export const SET_CONTROLSOPTION = 'SET_CONTROLSOPTION'
export const SET_WXLOGINSTATUS = 'SET_WXLOGINSTATUS'
/* 用户管理 */
export const GET_USERLIST = 'GET_USERLIST'

// 登陆用户权限
export const GET_ROLEMODULES = 'GET_ROLEMODULES'

// 聊天会话
export const GET_HASWXUSERLIST = 'GET_HASWXUSERLIST'
export const GET_WXUSERTAB = 'GET_WXUSERTAB'
export const SET_CHATLOGSHOW = 'SET_CHATLOGSHOW'
export const SET_HASCHECKLOADING = 'SET_HASCHECKLOADING'
export const SET_LOGINWXUSERINFO = 'SET_LOGINWXUSERINFO'
export const SET_REDIRECTURITYPE = 'SET_REDIRECTURITYPE'
export const SET_SYNCKEY = 'SET_SYNCKEY'
export const GET_CHATRECORDS = 'GET_CHATRECORDS'
export const SET_USERMEMBERLIST = 'SET_USERMEMBERLIST'
export const SET_CHATUSERLIST = 'SET_CHATUSERLIST'
export const SET_ACTIVEUSER = 'SET_ACTIVEUSER'
export const SET_ACTIVEINDEX = 'SET_ACTIVEINDEX'
export const SET_ACTIVEMESSAGELIST = 'SET_ACTIVEMESSAGELIST'
export const SET_USERCHATLOG = 'SET_USERCHATLOG'
export const START_CHECKWEBSYNC = 'START_CHECKWEBSYNC'
export const SET_UPDATEHASWXUSERLIST = 'SET_UPDATEHASWXUSERLIST'

// 权限列表
export const GET_ALLMENULIST = 'GET_ALLMENULIST'
